version: '1.0'
services:
  app:
    build: .
    command: npm start
    env:
      HTTP_PORT: 8080
    command: node index.js
    services:
      - port: ${{ HTTP_PORT }}
    volumes:
      - .:/app
      - /app/node_modules
    websocket:
    command: npm start
    internal: true
    services:
      - port: 18650